[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Jax AI Stacks"
authors = [{name = "Joseph Barnes", email = "josephbarnes@google.com"}]
dynamic = ["version", "description"]
